vendor/debian: fix UpdateExcusesTask
It looks like that requests' iter_lines(decode_unicode=True) doesn't work
as expected with version 2.0 deployed on tracker.debian.org and doesn't
always return unicode strings. So we bring back the manual decode in the
case where we get a binary type.

Regression introduced in 0e516aae884321adf78f2e904dc0e4ff3f9defe9.

The failure was this one:

Traceback (most recent call last):
  File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/tasks.py", line 518, in run
    task.execute()
  File "/srv/tracker.debian.org/distro-tracker/distro_tracker/vendor/debian/tracker_tasks.py", line 951, in execute
    result = self._get_excuses_and_problems(content_lines)
  File "/srv/tracker.debian.org/distro-tracker/distro_tracker/vendor/debian/tracker_tasks.py", line 859, in _get_excuses_and_problems
    if '</ul>' in line:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 19: ordinal not in range(128)