ci: fix functional tests
Finally, we run them again on stretch. We had to run them as nobody
instead of root to let chromium run and we had to pass --no-sandbox
to chromium.

Without this option, the tests are failing in the GitLab CI environment
(based on docker) with this unhelpful error:

    selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally