Adjust apt_pkg's usage for version in Debian 11 bullseye
source_records.files is now returning a dedicated object and
while expanding it to multiple values still does something close
to correct, the former "md5" parameter is always None which
is no longer accepted by the apt_pkg.AcquireFile() object.

Here's the kind of exception that this commit is fixing:

2021-10-25 11:45:55,169 [tracker_tasks/894504/140442881124160] ERROR: Problem extracting source files for hyperic-sigar, version 1.6.4+dfsg-6 version 1.6.4+dfsg-6
Traceback (most recent call last):
  File "/srv/tracker.debian.org/distro-tracker/distro_tracker/extract_source_files/tracker_tasks.py", line 110, in execute_main
    self.extract_files(srcpkg, files_to_extract)
  File "/srv/tracker.debian.org/distro-tracker/distro_tracker/extract_source_files/tracker_tasks.py", line 66, in extract_files
    source_directory = self.cache.retrieve_source(
  File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/utils/packages.py", line 684, in retrieve_source
    retrieved_files = self._apt_acquire_package(
  File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/utils/packages.py", line 628, in _apt_acquire_package
    files.append(apt_pkg.AcquireFile(
TypeError: 'hash' value must be an apt_pkg.HashStringList or a string