core: handle corner-case where we no longer have any package entry
It's not clear how this happened but it did happen once at least:

File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/tasks.py" in run
  517.                     task.execute()
File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/tasks.py" in wrapper
  544.             func(self)
File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/retrieve_data.py" in execute
  942.                 versions.value = self._extract_versions_for_package(package)
File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/retrieve_data.py" in _extract_versions_for_package
  919.             'default_pool_url': package_name.main_entry.directory_url,

Exception Type: AttributeError
Exception Value: 'NoneType' object has no attribute 'directory_url'

File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/tasks.py" in run
  517.                     task.execute()
File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/tasks.py" in wrapper
  544.             func(self)
File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/retrieve_data.py" in execute
  999.                 binaries.value = self._get_all_binaries(package)
File "/srv/tracker.debian.org/distro-tracker/distro_tracker/core/retrieve_data.py" in _get_all_binaries
  969.         repository = package.main_entry.repository

Exception Type: AttributeError
Exception Value: 'NoneType' object has no attribute 'repository'