Decode the error string returned by python-apt
Without this fix, a missing file (in a French environment) resulted
in this stack trace:
2014-07-03 07:08:21,709 ERROR: Problem extracting source files for scantailor, version 0.9.11.1-2 version 0.9.11.1-2
Traceback (most recent call last):
  File "/home/rhertzog/deb/core/distro-tracker/distro_tracker/extract_source_files/tracker_tasks.py", line 138, in execute
    self.extract_files(source_package)
  File "/home/rhertzog/deb/core/distro-tracker/distro_tracker/extract_source_files/tracker_tasks.py", line 69, in extract_files
    debian_directory_only=True)
  File "/home/rhertzog/deb/core/distro-tracker/distro_tracker/core/utils/packages.py", line 601, in retrieve_source
    source_records, dest_dir_path, debian_directory_only)
  File "/home/rhertzog/deb/core/distro-tracker/distro_tracker/core/utils/packages.py", line 564, in _apt_acquire_package
    file=item.destfile, error=item.error_text))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)

And with the fix, we get something better:
[...]
  File "/home/rhertzog/deb/core/distro-tracker/distro_tracker/core/utils/packages.py", line 565, in _apt_acquire_package
    file=item.destfile, error=item.error_text.decode('utf-8')))
SourcePackageRetrieveError: Could not retrieve file /home/rhertzog/deb/core/distro-tracker/data/cache/apt-cache/packages/g/gromacs/gromacs_5.0-2.debian.tar.xz: Fichier non trouv\xe9