test: improve tests when BASE_DIR is /tmp/distro-tracker
Running the tests from a checkout in /tmp/distro-tracker can lead
to unexpected errors (see below), we're now checking with a trailing
slash to avoid being trapped by the common prefix.

FAIL: test_temp_dirs_outside_of_base_path (distro_tracker.test.tests.TempDirsOnTestCase)
Test that the settings no longer point inside the base path.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/distro-tracker/distro_tracker/test/tests.py", line 57, in test_temp_dirs_outside_of_base_path
    getattr(settings, name))
AssertionError: '/tmp/distro-tracker' unexpectedly found in '/tmp/distro-tracker-tests-gtnifjiw/static'